receivers:
  otlp:
    protocols:
      grpc:

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
  batch:

exporters:
  # 'logging' is replaced by 'debug'
  debug:
    verbosity: normal # 'normal' is equivalent to the old 'info'/'warn' levels
  otlp/elastic:
    endpoint: "apm-server:8200"
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch] # Added memory_limiter to the pipeline
      exporters: [debug, otlp/elastic]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch] # Added memory_limiter to the pipeline
      exporters: [debug, otlp/elastic]